/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtlFactura;
import Controlador.CtlHospedaje;
import Controlador.CtlOpiniones;
import Controlador.CtlReserva;
import Excepcion.BuscarHuespedException;
import Excepcion.DatosIncompletosException;
import Excepcion.FacturacionException;
import Excepcion.GuardarOpinionesException;
import Excepcion.ModificarCuentaPersonalException;
import Modelo.Hospedaje;
import Modelo.Huesped;
import Modelo.ReservaHospedaje;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mateo
 */
public class FrmFacturacion extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuRecepcionista
     */
    private Huesped huesped = null;
    private CtlFactura controlador;
    private CtlHospedaje controladorHospedaje;
    private CtlReserva controladorReserva;
    private CtlOpiniones controladorOpiniones;
    int idReservacion = 0;
    String valorPgar = null;

    public FrmFacturacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public FrmFacturacion(Huesped huesped) {
        this.huesped = huesped;
        initComponents();
        this.controlador = new CtlFactura();
        this.controladorOpiniones = new CtlOpiniones();
        this.controladorHospedaje = new CtlHospedaje();
        this.controladorReserva = new CtlReserva();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        cargarInfo(huesped);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblCedulahuesped = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblCedulahuesped2 = new javax.swing.JLabel();
        txtValorPagar = new javax.swing.JTextField();
        btnGenerarValor = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblReservas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblReserva = new javax.swing.JTable();
        lblProductos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SpnCalidad = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        SpnVeracidad = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        SpnLimpieza = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        SpnUbicacion = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentarios = new javax.swing.JTextArea();
        btnEncuesta = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        lblCedulahuesped3 = new javax.swing.JLabel();
        txtValorNoche = new javax.swing.JTextField();
        lblCedulahuesped4 = new javax.swing.JLabel();
        txtGastosLimpieza = new javax.swing.JTextField();
        lblCedulahuesped5 = new javax.swing.JLabel();
        txtPlataforma = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        lblCedulahuesped6 = new javax.swing.JLabel();
        txtCuentaBancaria = new javax.swing.JTextField();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logousuarios.png"))); // NOI18N

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("NOMBRE COMPLETO");

        lblCedula.setBackground(new java.awt.Color(255, 255, 255));
        lblCedula.setForeground(new java.awt.Color(255, 255, 255));
        lblCedula.setText("CEDULA");

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setForeground(new java.awt.Color(102, 0, 0));
        btnSalir.setText("Regresar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(392, 392, 392))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(lblCedula)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addGap(5, 5, 5))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCedulahuesped.setBackground(new java.awt.Color(255, 255, 255));
        lblCedulahuesped.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCedulahuesped.setForeground(new java.awt.Color(0, 0, 0));
        lblCedulahuesped.setText("Cedula Huesped :");

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setForeground(new java.awt.Color(102, 0, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblCedulahuesped2.setBackground(new java.awt.Color(255, 255, 255));
        lblCedulahuesped2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCedulahuesped2.setForeground(new java.awt.Color(0, 0, 0));
        lblCedulahuesped2.setText("VALOR A PAGAR");

        txtValorPagar.setEnabled(false);

        btnGenerarValor.setBackground(new java.awt.Color(255, 255, 255));
        btnGenerarValor.setForeground(new java.awt.Color(102, 0, 0));
        btnGenerarValor.setText("GENERAR VALOR");
        btnGenerarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarValorActionPerformed(evt);
            }
        });

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("FACTURACION");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        lblReservas.setBackground(new java.awt.Color(255, 255, 255));
        lblReservas.setForeground(new java.awt.Color(0, 0, 0));
        lblReservas.setText("RESERVAS ACTIVAS");

        jtblReserva.setBackground(new java.awt.Color(255, 255, 255));
        jtblReserva.setForeground(new java.awt.Color(0, 0, 0));
        jtblReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Reserva", "Fecha Reservacion", "Habitacion", "Estado", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblReservaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblReserva);

        lblProductos.setBackground(new java.awt.Color(255, 255, 255));
        lblProductos.setForeground(new java.awt.Color(0, 0, 0));
        lblProductos.setText("PRODUCTOS");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Calidad del servicio :");

        SpnCalidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        SpnCalidad.setEnabled(false);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Veracidad:");

        SpnVeracidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        SpnVeracidad.setEnabled(false);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Limpieza:");

        SpnLimpieza.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        SpnLimpieza.setEnabled(false);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ubicacion:");

        SpnUbicacion.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        SpnUbicacion.setEnabled(false);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Comentarios,Quejas o Recomendaciones:");

        txtComentarios.setBackground(new java.awt.Color(255, 255, 255));
        txtComentarios.setColumns(20);
        txtComentarios.setForeground(new java.awt.Color(0, 0, 0));
        txtComentarios.setRows(5);
        txtComentarios.setEnabled(false);
        jScrollPane2.setViewportView(txtComentarios);

        btnEncuesta.setBackground(new java.awt.Color(255, 255, 255));
        btnEncuesta.setForeground(new java.awt.Color(102, 0, 0));
        btnEncuesta.setText("ENVIAR ENCUESTA");
        btnEncuesta.setEnabled(false);
        btnEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SpnVeracidad, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(SpnCalidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SpnLimpieza, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(SpnUbicacion))
                        .addGap(42, 42, 42)
                        .addComponent(btnEncuesta))
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblReservas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SpnLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpnCalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SpnVeracidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(SpnUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPagar.setBackground(new java.awt.Color(255, 255, 255));
        btnPagar.setForeground(new java.awt.Color(102, 0, 0));
        btnPagar.setText("PAGAR");
        btnPagar.setEnabled(false);
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        lblCedulahuesped3.setBackground(new java.awt.Color(255, 255, 255));
        lblCedulahuesped3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCedulahuesped3.setForeground(new java.awt.Color(0, 0, 0));
        lblCedulahuesped3.setText("VALOR LA NOCHE");

        txtValorNoche.setEnabled(false);

        lblCedulahuesped4.setBackground(new java.awt.Color(255, 255, 255));
        lblCedulahuesped4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCedulahuesped4.setForeground(new java.awt.Color(0, 0, 0));
        lblCedulahuesped4.setText("VALOR GASTOS LIMPIEZA");

        txtGastosLimpieza.setEnabled(false);

        lblCedulahuesped5.setBackground(new java.awt.Color(255, 255, 255));
        lblCedulahuesped5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCedulahuesped5.setForeground(new java.awt.Color(0, 0, 0));
        lblCedulahuesped5.setText("VALOR PLATAFORMA");

        txtPlataforma.setEnabled(false);

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setForeground(new java.awt.Color(102, 0, 0));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblCedulahuesped6.setBackground(new java.awt.Color(255, 255, 255));
        lblCedulahuesped6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCedulahuesped6.setForeground(new java.awt.Color(0, 0, 0));
        lblCedulahuesped6.setText("CUENTA BANCARIA");

        txtCuentaBancaria.setBackground(new java.awt.Color(255, 255, 255));
        txtCuentaBancaria.setForeground(new java.awt.Color(0, 0, 0));
        txtCuentaBancaria.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCedulahuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCedulahuesped5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCedulahuesped4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCedulahuesped3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCedulahuesped6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGenerarValor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(lblCedulahuesped2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtValorPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtPlataforma, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtGastosLimpieza)
                            .addComponent(txtValorNoche)
                            .addComponent(txtCuentaBancaria))
                        .addGap(52, 52, 52))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblTitulo)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCedulahuesped)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(33, 33, 33)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnGenerarValor, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lblCedulahuesped6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCuentaBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblCedulahuesped3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorNoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCedulahuesped4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGastosLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCedulahuesped5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCedulahuesped2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPagar)
                            .addComponent(btnCancelar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        FrmMenuHuesped menuHuesped = new FrmMenuHuesped(huesped);
        menuHuesped.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            huesped = controlador.buscarHuesped(controlador.obtenerDatoJtextFile(txtCedula));
            listarReserva(huesped);
            imprimir(huesped.getNombreCompleto() + " Encontrado correctamente");
        } catch (BuscarHuespedException | DatosIncompletosException ex) {
            imprimir(ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGenerarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarValorActionPerformed
        if (idReservacion == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione una reserva para generarle el total a pagar");
        } else {
            txtCuentaBancaria.setEnabled(true);
            txtValorNoche.setText(controlador.generarValorHabitacion(idReservacion));
            txtGastosLimpieza.setText(controlador.generarValorLimpieza(idReservacion));
            txtPlataforma.setText(controlador.generarValorPlataforma(idReservacion));
            txtValorPagar.setText(controlador.genararValorTotal(idReservacion));
            btnPagar.setEnabled(true);
            btnCancelar.setEnabled(true);
        }
    }//GEN-LAST:event_btnGenerarValorActionPerformed

    private void jtblReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblReservaMouseClicked
        int filaSeleccionada = jtblReserva.getSelectedRow();

        if (filaSeleccionada == -1) {
            imprimir("No se ha seleccionado ninguna fila");
        } else {
            int idreservacion = (int) jtblReserva.getValueAt(filaSeleccionada, 0);
            this.idReservacion = idreservacion;

        }
    }//GEN-LAST:event_jtblReservaMouseClicked

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        try {
            ReservaHospedaje reserva = controlador.buscarReservaId(idReservacion);
            String valorpagado = controlador.obtenerDatoJtextFile(txtValorPagar);
            String cuentabancaria = controlador.obtenerDatoJtextFile(txtCuentaBancaria);
            controlador.pagar(reserva, huesped.getId(), valorpagado, cuentabancaria);
            JOptionPane.showMessageDialog(null, "Se realizó el Pago correctamente");
            cargarEncuesta();
        } catch (DatosIncompletosException | FacturacionException | ModificarCuentaPersonalException ex) {
            imprimir(ex.getMessage());
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarPago();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncuestaActionPerformed
        try {
            String calidad = SpnCalidad.getValue().toString();
            String veracidad = SpnVeracidad.getValue().toString();
            String limpieza = SpnLimpieza.getValue().toString();
            String ubicacion = SpnUbicacion.getValue().toString();
            String comentarios = controladorOpiniones.obtenerDatoJtextArea(txtComentarios);
            double valorfinal = controladorOpiniones.calificacionfinal(calidad, veracidad, limpieza, ubicacion);
            ReservaHospedaje reserva = controlador.buscarReservaId(idReservacion);

            String valorcompleto = valorfinal + "";
            controladorOpiniones.guardarOpiniones(huesped.getId(), reserva.getIdHabitacion(), valorcompleto, comentarios);
            imprimir("Se guardó comentario correctamente");
            limpiarEncuesta();
        } catch (DatosIncompletosException | GuardarOpinionesException ex) {
            imprimir(ex.getMessage());
        }
    }//GEN-LAST:event_btnEncuestaActionPerformed
    private void cargarInfo(Huesped huespedes) {

        lblCedula.setText(huespedes.getCedula());
        lblNombre.setText(huespedes.getNombreCompleto());
        txtCedula.setText(huespedes.getCedula());
        txtCedula.setEnabled(false);

    }

    private void cargarEncuesta() {
        SpnCalidad.setEnabled(true);
        SpnLimpieza.setEnabled(true);
        SpnVeracidad.setEnabled(true);
        SpnUbicacion.setEnabled(true);
        txtComentarios.setEnabled(true);
        txtCuentaBancaria.setEnabled(false);
        btnSalir.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnPagar.setEnabled(false);
        btnEncuesta.setEnabled(true);
        btnBuscar.setEnabled(false);
        btnGenerarValor.setEnabled(false);
        jtblReserva.setEnabled(false);
    }

    private void imprimir(String v) {
        JOptionPane.showMessageDialog(null, v);
    }

    private void listarReserva(Huesped huesped) {
        jtblReserva.setModel(controlador.listaElementosReserva(huesped.getId()));
    }

    private void limpiarPago() {
        txtCuentaBancaria.setText("");
        txtCuentaBancaria.setEnabled(false);
        txtValorNoche.setText("");
        txtGastosLimpieza.setText("");
        txtPlataforma.setText("");
        txtValorPagar.setText("");
    }

    private void limpiarEncuesta() {
        btnSalir.setEnabled(true);
        btnBuscar.setEnabled(true);
        jtblReserva.setEnabled(true);
        jtblReserva.setModel(new DefaultTableModel());
        btnGenerarValor.setEnabled(true);
        txtCuentaBancaria.setText("");
        txtValorNoche.setText("");
        txtGastosLimpieza.setText("");
        txtPlataforma.setText("");
        txtValorPagar.setText("");
        SpnCalidad.setValue(0);
        SpnCalidad.setEnabled(false);
        SpnLimpieza.setValue(0);
        SpnLimpieza.setEnabled(false);
        SpnVeracidad.setValue(0);
        SpnVeracidad.setEnabled(false);
        SpnUbicacion.setValue(0);
        SpnUbicacion.setEnabled(false);
        txtComentarios.setText("");
        txtComentarios.setEnabled(false);
        btnEncuesta.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFacturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpnCalidad;
    private javax.swing.JSpinner SpnLimpieza;
    private javax.swing.JSpinner SpnUbicacion;
    private javax.swing.JSpinner SpnVeracidad;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEncuesta;
    private javax.swing.JButton btnGenerarValor;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable jtblReserva;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCedulahuesped;
    private javax.swing.JLabel lblCedulahuesped2;
    private javax.swing.JLabel lblCedulahuesped3;
    private javax.swing.JLabel lblCedulahuesped4;
    private javax.swing.JLabel lblCedulahuesped5;
    private javax.swing.JLabel lblCedulahuesped6;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblReservas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextArea txtComentarios;
    private javax.swing.JTextField txtCuentaBancaria;
    private javax.swing.JTextField txtGastosLimpieza;
    private javax.swing.JTextField txtPlataforma;
    private javax.swing.JTextField txtValorNoche;
    private javax.swing.JTextField txtValorPagar;
    // End of variables declaration//GEN-END:variables
}
