/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtlAnfitrion;
import Excepcion.BuscarAnfitrionException;
import Excepcion.CargarImagenException;
import Excepcion.CedulaAdministradorException;
import Excepcion.CedulaException;
import Excepcion.CedulaHuespedException;
import Excepcion.ComboBoxException;
import Excepcion.DatosIncompletosException;
import Excepcion.GuardarAnfitrionException;
import Excepcion.ModificarAnfitrionException;
import Modelo.Administrador;
import Modelo.Anfitrion;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mateo
 */
public class FrmGestionAnfitrion extends javax.swing.JFrame {

    private Administrador administrador;
    private CtlAnfitrion controlador;
    private String estado;

    public FrmGestionAnfitrion() {
        controlador = new CtlAnfitrion();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        btnRegistrar.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnCancelar.setEnabled(false);
    }

    public FrmGestionAnfitrion(Administrador administrador) {
        controlador = new CtlAnfitrion();
        this.administrador = administrador;
        initComponents();

        this.setLocationRelativeTo(null);
        this.setResizable(false);

        btnCancelar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnModificar.setEnabled(false);
        tblLista.setEnabled(true);
        txtRuta.setEditable(false);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblNombreCompleto = new javax.swing.JLabel();
        lblResidencia = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtResidencia = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblFiltrar = new javax.swing.JLabel();
        CbxFiltrar = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtFiltrar = new javax.swing.JTextField();
        btnSeleccionarImagen = new javax.swing.JButton();
        txtRuta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBiografia = new javax.swing.JTextArea();
        lblmagen = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtIdioma = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblCedula.setForeground(new java.awt.Color(0, 0, 0));
        lblCedula.setText("Cedula :");

        txtCedula.setBackground(new java.awt.Color(255, 255, 255));
        txtCedula.setForeground(new java.awt.Color(0, 0, 0));
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        lblNombreCompleto.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreCompleto.setText("Nombre Completo :");

        lblResidencia.setForeground(new java.awt.Color(0, 0, 0));
        lblResidencia.setText("Residencia:");

        txtNombreCompleto.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreCompleto.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreCompleto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreCompletoKeyTyped(evt);
            }
        });

        lblTelefono.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefono.setText("Idioma:");

        txtResidencia.setBackground(new java.awt.Color(255, 255, 255));
        txtResidencia.setForeground(new java.awt.Color(0, 0, 0));
        txtResidencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResidenciaKeyTyped(evt);
            }
        });

        lblContrasena.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasena.setText("Contraseña :");

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setForeground(new java.awt.Color(0, 0, 0));

        tblLista.setBackground(new java.awt.Color(255, 255, 255));
        tblLista.setForeground(new java.awt.Color(0, 0, 0));
        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cedula", "Nombre Completo", "Residencia", "Idioma", "Contrasena", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblLista);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane1.setViewportView(jPanel2);

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(255, 255, 255));
        btnModificar.setForeground(new java.awt.Color(0, 0, 0));
        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("GESTION DE ANFITRION");

        lblFiltrar.setForeground(new java.awt.Color(0, 0, 0));
        lblFiltrar.setText("Filtrar tabla por :");

        CbxFiltrar.setBackground(new java.awt.Color(255, 255, 255));
        CbxFiltrar.setForeground(new java.awt.Color(0, 0, 0));
        CbxFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Cedula", "Estado" }));

        btnFiltrar.setBackground(new java.awt.Color(255, 255, 255));
        btnFiltrar.setForeground(new java.awt.Color(0, 0, 0));
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtFiltrar.setBackground(new java.awt.Color(255, 255, 255));
        txtFiltrar.setForeground(new java.awt.Color(0, 0, 0));
        txtFiltrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltrarKeyTyped(evt);
            }
        });

        btnSeleccionarImagen.setBackground(new java.awt.Color(255, 255, 255));
        btnSeleccionarImagen.setForeground(new java.awt.Color(0, 0, 0));
        btnSeleccionarImagen.setText("Seleccionar imagen");
        btnSeleccionarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarImagenActionPerformed(evt);
            }
        });

        txtRuta.setBackground(new java.awt.Color(255, 255, 255));
        txtRuta.setForeground(new java.awt.Color(0, 0, 0));
        txtRuta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutaKeyTyped(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Biografia:");

        txtBiografia.setBackground(new java.awt.Color(255, 255, 255));
        txtBiografia.setColumns(20);
        txtBiografia.setForeground(new java.awt.Color(0, 0, 0));
        txtBiografia.setRows(5);
        jScrollPane3.setViewportView(txtBiografia);

        lblmagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo blanco.gif"))); // NOI18N
        lblmagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblmagen.setMaximumSize(new java.awt.Dimension(4, 4));
        lblmagen.setMinimumSize(new java.awt.Dimension(4, 4));

        txtIdioma.setBackground(new java.awt.Color(255, 255, 255));
        txtIdioma.setColumns(20);
        txtIdioma.setForeground(new java.awt.Color(0, 0, 0));
        txtIdioma.setRows(5);
        jScrollPane4.setViewportView(txtIdioma);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(280, 280, 280))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCedula)
                            .addComponent(lblNombreCompleto)
                            .addComponent(lblTelefono)
                            .addComponent(lblContrasena)
                            .addComponent(lblResidencia)
                            .addComponent(lblFiltrar)
                            .addComponent(jLabel5))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtResidencia)
                            .addComponent(txtNombreCompleto)
                            .addComponent(txtPassword)
                            .addComponent(txtCedula)
                            .addComponent(CbxFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(btnSeleccionarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(47, 47, 47))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblmagen, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 106, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCedula)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreCompleto)
                            .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblResidencia)
                            .addComponent(txtResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefono)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContrasena)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblmagen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSeleccionarImagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addGap(14, 14, 14)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar)
                        .addGap(14, 14, 14)
                        .addComponent(btnEliminar)
                        .addGap(15, 15, 15)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltrar)
                    .addComponent(CbxFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar)
                    .addComponent(btnActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtPassword.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {

            String cedula = controlador.obtenerDatoJtextFile(txtCedula);
            String nombrecompleto = controlador.obtenerDatoJtextFile(txtNombreCompleto);
            String residencia = controlador.obtenerDatoJtextFile(txtResidencia);
            String idioma = controlador.obtenerDatoJtextArea(txtIdioma);
            String contrasena = controlador.obtenerDatoJtextFile(txtPassword);
            String biografia = controlador.obtenerDatoJtextArea(txtBiografia);
            String estado = "No Disponible";

            controlador.modificarAnfitrion(cedula, nombrecompleto, residencia, idioma, contrasena, biografia, estado);
            JOptionPane.showMessageDialog(null, "Se Elimino el anfitrion " + nombrecompleto + " correctamente");
            listar();
            vaciarCampos();
            btnRegistrar.setEnabled(true);
            btnModificar.setEnabled(false);
            btnBuscar.setEnabled(true);
            btnEliminar.setEnabled(false);
            txtCedula.setEnabled(true);
            btnCancelar.setEnabled(false);
        } catch (CedulaException | DatosIncompletosException | ModificarAnfitrionException | BuscarAnfitrionException ex) {
            imprimir(ex.getMessage());
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        FrmAdministrador vista = new FrmAdministrador(administrador);
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtNombreCompletoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCompletoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && c != ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreCompletoKeyTyped

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        try {
            String opcion = CbxFiltrar.getSelectedItem().toString();
            String accion = controlador.obtenerDatoJtextFile(txtFiltrar);
            tblLista.setModel(controlador.filtrar(opcion, accion));
        } catch (ComboBoxException | DatosIncompletosException | NumberFormatException ex) {
            imprimir(ex.getMessage());
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        listar();
        CbxFiltrar.setSelectedItem("Seleccione");
        txtFiltrar.setText(null);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            File ruta = new File(txtRuta.getText());
            String cedula = controlador.obtenerDatoJtextFile(txtCedula);
            String nombrecompleto = controlador.obtenerDatoJtextFile(txtNombreCompleto);
            String residencia = controlador.obtenerDatoJtextFile(txtResidencia);
            String idioma = controlador.obtenerDatoJtextArea(txtIdioma);
            String contrasena = controlador.obtenerDatoJtextFile(txtPassword);
            String biografia = controlador.obtenerDatoJtextArea(txtBiografia);
            String estado = "activo";

            controlador.guardarAnfitrion(ruta, cedula, nombrecompleto, residencia, idioma, contrasena, biografia, estado);
            JOptionPane.showMessageDialog(null, "Se guardó el Anfitrion " + nombrecompleto + " correctamente");
            vaciarCampos();
            listar();
        } catch (CargarImagenException | GuardarAnfitrionException | CedulaException | DatosIncompletosException | CedulaAdministradorException | CedulaHuespedException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnRegistrar.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnCancelar.setEnabled(false);
        txtCedula.setEnabled(true);
        vaciarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            Anfitrion anfitrion = controlador.buscarAnfitrion(controlador.obtenerDatoJtextFile(txtCedula));
            imprimir("Se encontro el huesped " + anfitrion.getNombreCompleto() + " correctamente");
            lblmagen.setIcon(new ImageIcon(controlador.cargarImagenBufferedImage(anfitrion.getFoto())));
            cargatinformacion(anfitrion);
            btnRegistrar.setEnabled(false);
            btnEliminar.setEnabled(true);
            btnModificar.setEnabled(true);
            btnBuscar.setEnabled(false);
            txtCedula.setEnabled(false);
            btnCancelar.setEnabled(true);
        } catch (DatosIncompletosException | BuscarAnfitrionException | CargarImagenException ex) {
            imprimir(ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {

            String cedula = controlador.obtenerDatoJtextFile(txtCedula);
            String nombrecompleto = controlador.obtenerDatoJtextFile(txtNombreCompleto);
            String residencia = controlador.obtenerDatoJtextFile(txtResidencia);
            String idioma = controlador.obtenerDatoJtextArea(txtIdioma);
            String contrasena = controlador.obtenerDatoJtextFile(txtPassword);
            String biografia = controlador.obtenerDatoJtextArea(txtBiografia);
            String Estado = estado;

            if (controlador.obtenerDatoJtextFile(txtRuta) != null) {
                File ruta = new File(txtRuta.getText());
                controlador.modificarAnfitrion2(cedula, ruta, nombrecompleto, residencia, idioma, contrasena, biografia, Estado);
                JOptionPane.showMessageDialog(null, "Se Modifico el Anfitrion " + nombrecompleto + " correctamente");
                listar();
                vaciarCampos();
                btnRegistrar.setEnabled(true);
                btnEliminar.setEnabled(false);
                btnModificar.setEnabled(false);
                btnBuscar.setEnabled(true);
                txtCedula.setEnabled(true);
                btnCancelar.setEnabled(false);

            } else {
                controlador.modificarAnfitrion(cedula, nombrecompleto, residencia, idioma, contrasena, biografia, Estado);
                JOptionPane.showMessageDialog(null, "Se Modifico el Anfitrion " + nombrecompleto + " correctamente");
                listar();
                vaciarCampos();
                btnRegistrar.setEnabled(true);
                btnEliminar.setEnabled(false);
                btnModificar.setEnabled(false);
                btnBuscar.setEnabled(true);
                txtCedula.setEnabled(true);
                btnCancelar.setEnabled(false);
            }
        } catch (CargarImagenException | CedulaException | DatosIncompletosException | ModificarAnfitrionException | BuscarAnfitrionException ex) {
            imprimir(ex.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtFiltrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltrarKeyTyped
        char c = evt.getKeyChar();
        if (c == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_txtFiltrarKeyTyped

    private void btnSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarImagenActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setDialogTitle("Seleccione la imagen de la habitación");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");//se le asigna un filtro
        fileChooser.setFileFilter(filtro);
        int condi = fileChooser.showOpenDialog(this);
        if (condi == JFileChooser.APPROVE_OPTION) {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            //     rsscalelabel.RSScaleLabel.setScaleLabel(lblmagen, fileChooser.getSelectedFile().toString());//carga la imagen
            try {
                lblmagen.setIcon(new ImageIcon(controlador.cargarImagenBufferedImage(controlador.cargarImagenBytes(new File(ruta)))));
            } catch (CargarImagenException ex) {
                imprimir(ex.getMessage());
            }

            txtRuta.setText(ruta);

        }
    }//GEN-LAST:event_btnSeleccionarImagenActionPerformed

    private void txtRutaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaKeyTyped

    private void txtResidenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResidenciaKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') && c != '_' && c != '@' && c != '.' && c != '-') {
            evt.consume();
        }
    }//GEN-LAST:event_txtResidenciaKeyTyped

    public final void listar() {
        tblLista.setModel(controlador.listarElementos());
    }

    private void cargatinformacion(Anfitrion anfitrion) {
        txtCedula.setText(anfitrion.getCedula());
        txtNombreCompleto.setText(anfitrion.getNombreCompleto());
        txtResidencia.setText(anfitrion.getResidencia());
        txtIdioma.setText(anfitrion.getIdioma());
        txtPassword.setText(anfitrion.getContrasena());
        txtBiografia.setText(anfitrion.getBiografia());
        txtRuta.setText(null);
        estado = anfitrion.getEstado();
    }

    private void vaciarCampos() {
        txtCedula.setText(null);
        txtNombreCompleto.setText(null);
        txtResidencia.setText(null);
        txtIdioma.setText(null);
        txtPassword.setText(null);
        txtBiografia.setText(null);
        lblmagen.setIcon(null);
        estado = null;
    }

    private void imprimir(String v) {
        JOptionPane.showMessageDialog(null, v);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestionAnfitrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestionAnfitrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestionAnfitrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestionAnfitrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestionAnfitrion().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxFiltrar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionarImagen;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblFiltrar;
    private javax.swing.JLabel lblNombreCompleto;
    private javax.swing.JLabel lblResidencia;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblmagen;
    private javax.swing.JTable tblLista;
    private javax.swing.JTextArea txtBiografia;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtFiltrar;
    private javax.swing.JTextArea txtIdioma;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtResidencia;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
